TEXTS = {
    'uz': {
        'welcome': "🌟 <b>Xush kelibsiz, {name}!</b>\n\nSizni botimizda ko'rib turganimizdan xursandmiz. Bu yerda siz o'zingizga yoqqan kinolarni faqat kodini yuborish orqali topishingiz mumkin.\n\n🎬 <b>Kino kodini yuboring:</b>",
        'enter_code': "🔢 Iltimos, videoning raqamli kodini yuboring:",
        'search_name': "🔎 Iltimos, qidirish uchun nom yoki sarlavhani yuboring:",
        'help': "📖 <b>Qanday foydalanish kerak:</b>\n1. Shunchaki kino kodini yuboring (masalan: 657)\n2. Sifatni tanlang\n3. Videoni qabul qiling!\n\nKunlik limit: 5 ta so'rov.",
        'invalid_code': "❌ Noto'g'ri kod. Iltimos, faqat raqam yuboring.",
        'limit_reached': "⚠️ Kunlik limit tugadi. Ertaga qayta urinib ko'ring.",
        'not_found': "❌ Kod topilmadi. Iltimos, tekshirib qayta urinib ko'ring.",
        'select_quality': "🎬 Video kodi: {code}\nSarlavha: {title}\n\nSifatni tanlang:",
        'video_sent': "✅ Video muvaffaqiyatli yuborildi.",
        'sub_required': "❗ <b>Diqqat!</b> Botdan foydalanish uchun quyidagi kanallarga a'zo bo'lishingiz shart:",
        'sub_check': "✅ Obuna tasdiqlandi!",
        'sub_failed': "❌ Siz hali barcha kanallarga a'zo bo'lmagansiz!",
        'search_results': "🔎 <b>Qidiruv natijalari:</b>\n\n{results}\n\nVideoni olish uchun kodni yuboring.",
        'no_results': "❌ Bu nomga mos videolar topilmadi.",
        'btn_enter_code': "🎬 Kodni kiritish",
        'btn_search_name': "🔎 Nomi bo'yicha qidirish",
        'btn_help': "📜 Yordam",
        'btn_sub': "{n} - kanal",
        'btn_check_sub': "✅ Tasdiqlash",
        'lang_selected': "🇺🇿 O'zbek tili tanlandi.",
        'checking': "⏳ Tekshirilmoqda...",
        'btn_main_menu': "🏠 Asosiy menyu"
    },
    'uz_cyr': {
        'welcome': "🌟 <b>Хуш келибсиз, {name}!</b>\n\nСизни ботимизда кўриб турганимиздан хурсандмиз. Бу ерда сиз ўзингизга ёққан киноларни фақат кодини юбориш орқали топишингиз мумкин.\n\n🎬 <b>Кино кодини юборинг:</b>",
        'enter_code': "🔢 Илтимос, видеонинг рақаmli кодини юборинг:",
        'search_name': "🔎 Илтимос, қидириш учун ном ёки сарлавҳани юборинг:",
        'help': "📖 <b>Қандай фойдаланиш керак:</b>\n1. Шунчаки кино кодини юборинг (масалан: 657)\n2. Сифатни танланг\n3. Видеони қабул қилинг!\n\nКунлик лимит: 5 та сўров.",
        'invalid_code': "❌ Нотўғри код. Илтимос, фақат рақам юборинг.",
        'limit_reached': "⚠️ Кунлик лимит тугади. Эртага қайта уриниб кўринг.",
        'not_found': "❌ Код топилмади. Илтимос, текшириб қайта уриниб кўринг.",
        'select_quality': "🎬 Видео коди: {code}\nСарлавҳа: {title}\n\nСифатни танланг:",
        'video_sent': "✅ Видео мувaffaqiyatli юборилди.",
        'sub_required': "❗ <b>Диққат!</b> Ботдан фойдаланиш учун қуйидаги каналларга аъзо бўлишингиз шарт:",
        'sub_check': "✅ Обуна тасдиқланди!",
        'sub_failed': "❌ Сиз ҳали барча каналларга обуна бўлмагансиз.",
        'search_results': "🔎 <b>Қидирув натижалари:</b>\n\n{results}\n\nВидеони олиш учун кодни юборинг.",
        'no_results': "❌ Бу номга мос видеолар топилмади.",
        'btn_enter_code': "🎬 Кодни киритиш",
        'btn_search_name': "🔎 Номи бўйича қидириш",
        'btn_help': "📜 Ёрдам",
        'btn_sub': "{n} - канал",
        'btn_check_sub': "✅ Тасдиқлаш",
        'lang_selected': "🇺🇿 Ўзбек тили танланди.",
        'checking': "⏳ Текширилмоқда...",
        'btn_main_menu': "🏠 Асосий меню"
    },
    'ru': {
        'welcome': "🌟 <b>Добро пожаловать, {name}!</b>\n\nРады видеть вас. Здесь вы можете найти фильмы по коду.\n\n🎬 <b>Отправьте код фильма:</b>",
        'enter_code': "🔢 Пожалуйста, отправьте код:",
        'search_name': "🔎 Пожалуйста, отправьте название:",
        'help': "📖 <b>Помощь:</b>\nОтправьте код фильма для получения видео.",
        'invalid_code': "❌ Неверный код.",
        'limit_reached': "⚠️ Лимит исчерпан.",
        'not_found': "❌ Код не найден.",
        'select_quality': "🎬 Код: {code}\nЗаголовок: {title}\n\nВыберите качество:",
        'video_sent': "✅ Видео отправлено.",
        'sub_required': "❗ <b>Внимание!</b> Подпишитесь на каналы:",
        'sub_check': "✅ Подписка подтверждена!",
        'sub_failed': "❌ Вы не подписаны на все каналы.",
        'search_results': "🔎 <b>Результаты:</b>\n\n{results}",
        'no_results': "❌ Ничего не найдено.",
        'btn_enter_code': "🎬 Ввести код",
        'btn_search_name': "🔎 Поиск",
        'btn_help': "📜 Помощь",
        'btn_sub': "{n} - канал",
        'btn_check_sub': "✅ Проверить",
        'lang_selected': "🇷🇺 Выбран русский язык.",
        'checking': "⏳ Проверка...",
        'btn_main_menu': "🏠 Меню"
    },
    'en': {
        'welcome': "🌟 <b>Welcome, {name}!</b>\n\nFind your favorite movies by code.\n\n🎬 <b>Send the movie code:</b>",
        'enter_code': "🔢 Send the movie code:",
        'search_name': "🔎 Send the name or title:",
        'help': "📖 <b>How to use:</b>\nSend any movie code to get the video.",
        'invalid_code': "❌ Invalid code.",
        'limit_reached': "⚠️ Limit reached.",
        'not_found': "❌ Code not found.",
        'select_quality': "🎬 Code: {code}\nTitle: {title}\n\nSelect quality:",
        'video_sent': "✅ Video sent.",
        'sub_required': "❗ <b>Attention!</b> You must subscribe to our channels:",
        'sub_check': "✅ Subscription confirmed!",
        'sub_failed': "❌ Subscription check failed.",
        'search_results': "🔎 <b>Search Results:</b>\n\n{results}",
        'no_results': "❌ No videos found.",
        'btn_enter_code': "🎬 Enter Code",
        'btn_search_name': "🔎 Search",
        'btn_help': "📜 Help",
        'btn_sub': "{n} - channel",
        'btn_check_sub': "✅ Confirm",
        'lang_selected': "🇺🇸 English selected.",
        'checking': "⏳ Checking...",
        'btn_main_menu': "🏠 Main Menu"
    }
}
